nginx:
    image: nginx
    ports:
        - "80:80"
    links: 
        - phpfpm
    volumes: 
        - ./nginx/default:/etc/nginx/conf.d/default.conf

        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
phpfpm:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes: 
        - ./public:/usr/share/nginx/html